//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet_Management_Rental.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fleet_Management_Rental.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap national_ID {
            get {
                object obj = ResourceManager.GetObject("national-ID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2026_05_12_183545 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2026-05-12 183545", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2026_05_12_183648 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2026-05-12 183648", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2026_05_12_183724 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2026-05-12 183724", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2026_05_12_205119 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2026-05-12 205119", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2026_05_12_222107 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2026-05-12 222107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2026_05_12_222258 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2026-05-12 222258", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2026_05_12_222623 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2026-05-12 222623", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_15273_www_bing_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_15273_www.bing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_15273_www_bing1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_15273_www.bing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_16359_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_16359_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_21252_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_21252_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_22342_www_bing_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_22342_www.bing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_231433_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_231433_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_231724_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_231724_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_23217_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_23217_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_234643_www_bing_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_234643_www.bing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_21_4_2026_235037_www_bing_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_21-4-2026_235037_www.bing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_24_4_2026_02411_www_bing_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_24-4-2026_02411_www.bing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_24_4_2026_231817_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_24-4-2026_231817_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_24_4_2026_233131_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_24-4-2026_233131_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_02537_web_nen_wfglobal_org {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_02537_web.nen.wfglobal.org", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_215253_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_215253_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_215828_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_215828_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_22039_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_22039_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_223546_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_223546_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_224033_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_224033_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_224222_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_224222_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_224539_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_224539_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_22582_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_22582_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_22582_www_canva1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_22582_www.canva1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_26_4_2026_231633_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_26-4-2026_231633_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_01152_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_01152_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_01326_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_01326_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_01454_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_01454_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_01549_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_01549_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_01640_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_01640_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_01821_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_01821_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_01952_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_01952_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_02241_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_02241_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_27_4_2026_0225_www_canva_com {
            get {
                object obj = ResourceManager.GetObject("Screenshot_27-4-2026_0225_www.canva.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
